__all__ = (
    "WELCOME_EMAIL_SUBJECT",
    "WELCOME_EMAIL_TEMPLATE",
    "PASSWORD_RESET_EMAIL_SUBJECT",
    "PASSWORD_RESET_EMAIL_TEMPLATE",
    "PASSWORD_CHANGED_EMAIL_SUBJECT",
    "PASSWORD_CHANGED_EMAIL_TEMPLATE",
    "EMAIL_VERIFICATION_TEMPLATE",
    "EMAIL_VERIFICATION_SUBJECT",
)

from .email_verification import EMAIL_VERIFICATION_SUBJECT, EMAIL_VERIFICATION_TEMPLATE
from .password_changed import (
    PASSWORD_CHANGED_EMAIL_SUBJECT,
    PASSWORD_CHANGED_EMAIL_TEMPLATE,
)
from .password_reset import PASSWORD_RESET_EMAIL_SUBJECT, PASSWORD_RESET_EMAIL_TEMPLATE
from .welcome import WELCOME_EMAIL_SUBJECT, WELCOME_EMAIL_TEMPLATE
