x-env: &env
  environment:
    DATABASE__DB_NAME: ${DATABASE__DB_NAME:?error}
    DATABASE__DB_PASSWORD: ${DATABASE__DB_PASSWORD:?error}
    DATABASE__DB_USER: ${DATABASE__DB_USER:?error}
    DATABASE__DB_HOST: postgres-test
    DATABASE__DB_PORT: 5432

services:
  postgres-test:
    image: postgres:17-alpine
    ports:
      - "${DATABASE__DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE__DB_NAME:?error}
      POSTGRES_PASSWORD: ${DATABASE__DB_PASSWORD:?error}
      POSTGRES_USER: ${DATABASE__DB_USER:?error}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

  migrations:
    build:
      dockerfile: tests.Dockerfile
      context: .
      target: migrations
    <<: *env
    depends_on:
      postgres-test:
        condition: service_healthy

  tests:
    build:
      dockerfile: tests.Dockerfile
      context: .
      target: tests
    <<: *env
    depends_on:
      migrations:
        condition: service_completed_successfully
