[project]
name = "cheatsheet"
authors = [
    {name = "Denis Matsuga", email = "HitokiriDeepWeb@yandex.ru"},
    {name = "Konstantin Bojchenko", email = "Bojchenko_k@mail.ru"},
]
version = "0.1.0"
description = """
              Web app for development learning.
              Create, share, store, manage and subscribe to your favourite authors.
              """
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.12",
    "fastapi-users>=14.0.1",
    "orjson>=3.10.18",
    "pydantic-settings>=2.9.1",
    "pydantic[email]>=2.11.4",
    "sqlalchemy[asyncio]>=2.0.41",
    "uuid7>=0.1.0",
    "uvicorn[standard]>=0.34.2",
]

[dependency-groups]
dev = [
    "alembic>=1.16.1",
    "black>=25.1.0",
    "docker>=7.1.0",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-watcher>=0.4.3",
    "ruff>=0.11.11",
]

[tool.pytest.ini_options]
pythonpath = ". src"
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"
markers = [
    "integration: integration tests"
]

[tool.pytest-watcher]
clear = true
now = true

[tool.ruff.lint]
select = [
    "F",
    "W291",
    "W292",
    "W293",
    "W391",
    "B",
    "I",
    "FAST",
    "SIM",
    "N",
    "E",
]
ignore = ["B008", "N818"]
