"""add_social_networks_and_link_to_user_detail

Revision ID: 87c32910ae5b
Revises: 060e12e221ed
Create Date: 2025-12-10 20:34:28.426754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87c32910ae5b"
down_revision: Union[str, None] = "060e12e221ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "md_social_network",
        sa.Column(
            "social_network_id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("network_name", sa.String(length=20), nullable=False),
        sa.Column("network_image_url", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("social_network_id", name=op.f("pk_md_social_network")),
        sa.UniqueConstraint(
            "network_name", name=op.f("uq_md_social_network_network_name")
        ),
    )
    op.create_table(
        "user_to_social_network",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_network_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["social_network_id"],
            ["md_social_network.social_network_id"],
            name=op.f("fk_user_to_social_network_social_network_id_md_social_network"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_user_to_social_network_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "social_network_id",
            name=op.f("pk_user_to_social_network"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_to_social_network_user_id_user"),
        "user_to_social_network",
        type_="foreignkey",
    )
    op.drop_table("user_to_social_network")
    op.drop_table("md_social_network")
    # ### end Alembic commands ###
