"""rename model classes to use 'Model' suffix

Revision ID: 3434ab130e52
Revises: 60f438ae9add
Create Date: 2025-07-31 22:44:24.996773

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3434ab130e52"
down_revision: Union[str, None] = "60f438ae9add"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
