"""Create refresh_token_blacklist table

Revision ID: 75f086c23a41
Revises: 87c32910ae5b
Create Date: 2025-12-23 20:27:31.246458

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75f086c23a41"
down_revision: Union[str, None] = "87c32910ae5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_detail_to_social_network_user_id_user"),
        "user_detail_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_detail_to_social_network_user_id_user_detail"),
        "user_detail_to_social_network",
        "user_detail",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_detail_to_social_network_user_id_user_detail"),
        "user_detail_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_detail_to_social_network_user_id_user"),
        "user_detail_to_social_network",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
