"""fix cheatsheet, tag, cheatsheet_to_tag and create cheatsheet_stats tables

Revision ID: c741dd9e796b
Revises: d6cb0b611442
Create Date: 2025-06-01 18:22:24.947800

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c741dd9e796b"
down_revision: Union[str, None] = "d6cb0b611442"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cheatsheet_stats",
        sa.Column("cheatsheet_id", sa.BigInteger(), nullable=False),
        sa.Column("count_like", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("count_view", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "count_like >= 0",
            name=op.f("ck_cheatsheet_stats_ck_count_like_positive"),
        ),
        sa.CheckConstraint(
            "count_view >= 0",
            name=op.f("ck_cheatsheet_stats_ck_count_view_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["cheatsheet_id"],
            ["cheatsheet.cheatsheet_id"],
            name=op.f("fk_cheatsheet_stats_cheatsheet_id_cheatsheet"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cheatsheet_id", name=op.f("pk_cheatsheet_stats")),
    )
    op.add_column(
        "cheatsheet",
        sa.Column("is_public", sa.Boolean(), server_default="true", nullable=False),
    )
    op.alter_column(
        "md_tag",
        "tag_name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=35),
        existing_nullable=False,
    )
    op.create_index(
        "ix_tag_name_lower",
        "md_tag",
        [sa.literal_column("lower(tag_name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tag_name_lower", table_name="md_tag")
    op.alter_column(
        "md_tag",
        "tag_name",
        existing_type=sa.String(length=35),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("cheatsheet", "is_public")
    op.drop_table("cheatsheet_stats")
    # ### end Alembic commands ###
