"""add ON DELETE = CASCADE constraint to cheatsheet_to_tag table

Revision ID: 3aea9fda9873
Revises: 43a6f66a8aa3
Create Date: 2025-10-05 13:36:30.321882

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3aea9fda9873"
down_revision: Union[str, None] = "43a6f66a8aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cheatsheet_to_tag_cheatsheet_id_cheatsheet"),
        "cheatsheet_to_tag",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_cheatsheet_to_tag_tag_id_md_tag"),
        "cheatsheet_to_tag",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_cheatsheet_to_tag_tag_id_md_tag"),
        "cheatsheet_to_tag",
        "md_tag",
        ["tag_id"],
        ["tag_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_cheatsheet_to_tag_cheatsheet_id_cheatsheet"),
        "cheatsheet_to_tag",
        "cheatsheet",
        ["cheatsheet_id"],
        ["cheatsheet_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cheatsheet_to_tag_cheatsheet_id_cheatsheet"),
        "cheatsheet_to_tag",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_cheatsheet_to_tag_tag_id_md_tag"),
        "cheatsheet_to_tag",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_cheatsheet_to_tag_tag_id_md_tag"),
        "cheatsheet_to_tag",
        "md_tag",
        ["tag_id"],
        ["tag_id"],
    )
    op.create_foreign_key(
        op.f("fk_cheatsheet_to_tag_cheatsheet_id_cheatsheet"),
        "cheatsheet_to_tag",
        "cheatsheet",
        ["cheatsheet_id"],
        ["cheatsheet_id"],
    )
    # ### end Alembic commands ###
