"""create_refresh_token_status_model

Revision ID: bd475c306381
Revises: 2e3ff0a7bd9b
Create Date: 2025-11-20 23:04:40.105290

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd475c306381"
down_revision: Union[str, None] = "2e3ff0a7bd9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "md_refresh_token_status",
        sa.Column(
            "status_id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("status_id", name=op.f("pk_md_refresh_token_status")),
        sa.UniqueConstraint("name", name=op.f("uq_md_refresh_token_status_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("md_refresh_token_status")
    # ### end Alembic commands ###
