"""rename_status_name_column.py

Revision ID: fb1e2a7a4788
Revises: 060e12e221ed
Create Date: 2025-11-21 22:24:20.776252

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb1e2a7a4788"
down_revision: Union[str, None] = "060e12e221ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "md_refresh_token_status",
        sa.Column("status_name", sa.String(length=20), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_md_refresh_token_status_name"),
        "md_refresh_token_status",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_md_refresh_token_status_status_name"),
        "md_refresh_token_status",
        ["status_name"],
    )
    op.drop_column("md_refresh_token_status", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "md_refresh_token_status",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("uq_md_refresh_token_status_status_name"),
        "md_refresh_token_status",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_md_refresh_token_status_name"),
        "md_refresh_token_status",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("md_refresh_token_status", "status_name")
    # ### end Alembic commands ###
