"""Create user and user_detail tables, add foreign key to cheatsheet table

Revision ID: 2e3ff0a7bd9b
Revises: 3aea9fda9873
Create Date: 2025-11-12 19:15:07.667095

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e3ff0a7bd9b"
down_revision: Union[str, None] = "3aea9fda9873"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("user_name", sa.String(length=25), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user")),
        sa.UniqueConstraint("user_name", name=op.f("uq_user_user_name")),
    )
    op.create_table(
        "user_detail",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("profile_description", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_user_detail_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_detail")),
    )
    op.add_column("cheatsheet", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f("fk_cheatsheet_user_id_user"),
        "cheatsheet",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cheatsheet_user_id_user"), "cheatsheet", type_="foreignkey"
    )
    op.drop_column("cheatsheet", "user_id")
    op.drop_table("user_detail")
    op.drop_table("user")
    # ### end Alembic commands ###
