"""remove columns count_like and count_view in Cheatsheet model

Revision ID: 60f438ae9add
Revises: c741dd9e796b
Create Date: 2025-06-01 18:33:52.946000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60f438ae9add"
down_revision: Union[str, None] = "c741dd9e796b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cheatsheet", "count_view")
    op.drop_column("cheatsheet", "count_like")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cheatsheet",
        sa.Column(
            "count_like",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "cheatsheet",
        sa.Column(
            "count_view",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
