"""create refresh_token_blacklist model

Revision ID: 8577528d0c23
Revises: 87c32910ae5b
Create Date: 2025-12-26 19:38:13.484498

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8577528d0c23"
down_revision: Union[str, None] = "87c32910ae5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token_blacklist",
        sa.Column(
            "refresh_token_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("hashed_token", sa.Text(), nullable=False),
        sa.Column("hashed_fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["md_refresh_token_status.status_id"],
            name=op.f("fk_refresh_token_blacklist_status_id_md_refresh_token_status"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_refresh_token_blacklist_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "refresh_token_id", name=op.f("pk_refresh_token_blacklist")
        ),
    )
    op.drop_constraint(
        op.f("uq_md_refresh_token_status_name"),
        "md_refresh_token_status",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_md_refresh_token_status_status_name"),
        "md_refresh_token_status",
        ["status_name"],
    )
    op.drop_constraint(
        op.f("fk_user_detail_to_social_network_user_id_user"),
        "user_detail_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_detail_to_social_network_user_id_user_detail"),
        "user_detail_to_social_network",
        "user_detail",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_detail_to_social_network_user_id_user_detail"),
        "user_detail_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_detail_to_social_network_user_id_user"),
        "user_detail_to_social_network",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("uq_md_refresh_token_status_status_name"),
        "md_refresh_token_status",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_md_refresh_token_status_name"),
        "md_refresh_token_status",
        ["status_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("refresh_token_blacklist")
    # ### end Alembic commands ###
