"""Create md_oauth_service table

Revision ID: 7ad809af1b3f
Revises: 183084778036
Create Date: 2026-06-12 14:58:01.401797

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ad809af1b3f"
down_revision: Union[str, None] = "183084778036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "md_oauth_service",
        sa.Column(
            "oauth_service_id",
            sa.SmallInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("oauth_service_name", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "LENGTH(TRIM(oauth_service_name)) > 0",
            name=op.f("ck_md_oauth_service_ck_oauth_service_name_non_empty"),
        ),
        sa.PrimaryKeyConstraint("oauth_service_id", name=op.f("pk_md_oauth_service")),
        sa.UniqueConstraint(
            "oauth_service_name", name=op.f("uq_md_oauth_service_oauth_service_name")
        ),
    )
    op.create_index(
        "ix_oauth_service_name_lower",
        "md_oauth_service",
        [sa.literal_column("lower(oauth_service_name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_oauth_service_name_lower", table_name="md_oauth_service")
    op.drop_table("md_oauth_service")
    # ### end Alembic commands ###
