"""Add uniqueness for email field in user table

Revision ID: 183084778036
Revises: d2c9dbd4110c
Create Date: 2026-05-24 19:58:27.150447

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "183084778036"
down_revision: Union[str, None] = "d2c9dbd4110c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    # ### end Alembic commands ###
