"""Delete oauth_refresh_token table

Revision ID: 4651853d91ab
Revises: dde4203b1dc8
Create Date: 2026-06-29 20:01:10.074311

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4651853d91ab"
down_revision: Union[str, None] = "dde4203b1dc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_refresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_refresh_token",
        sa.Column(
            "refresh_token_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("oauth_account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status_id",
            sa.SMALLINT(),
            server_default=sa.text("'1'::smallint"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("hashed_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["oauth_account_id"],
            ["oauth_account.oauth_account_id"],
            name=op.f("fk_oauth_refresh_token_oauth_account_id_oauth_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["md_refresh_token_status.status_id"],
            name=op.f("fk_oauth_refresh_token_status_id_md_refresh_token_status"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "refresh_token_id", name=op.f("pk_oauth_refresh_token")
        ),
    )
    # ### end Alembic commands ###
