"""Restructure user tables, add oauth_account_table, registered_user

Revision ID: e0b33256e4bb
Revises: 8817d87357ae
Create Date: 2026-06-14 15:54:44.583098

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b33256e4bb"
down_revision: Union[str, None] = "8817d87357ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_account",
        sa.Column(
            "oauth_account_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("oauth_service_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oauth_service_id"],
            ["md_oauth_service.oauth_service_id"],
            name=op.f("fk_oauth_account_oauth_service_id_md_oauth_service"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_oauth_account_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("oauth_account_id", name=op.f("pk_oauth_account")),
        sa.UniqueConstraint(
            "oauth_service_id", "provider_user_id", name="uq_oauth_service_provider"
        ),
        sa.UniqueConstraint(
            "user_id", "oauth_service_id", name="uq_user_oauth_service"
        ),
    )
    op.create_table(
        "registered_user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_registered_user_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_registered_user")),
    )
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("registered_user")
    op.drop_table("oauth_account")
    # ### end Alembic commands ###
