"""Add gin indexes for cheatsheet table

Revision ID: d2c9dbd4110c
Revises: 2d3dc841c4e1
Create Date: 2026-05-23 23:11:18.573958

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2c9dbd4110c"
down_revision: Union[str, None] = "2d3dc841c4e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_cheatsheet_content_trgm",
        "cheatsheet",
        [sa.literal_column("content gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_cheatsheet_search_trgm",
        "cheatsheet",
        [sa.text("(title || ' ' || content) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_cheatsheet_title_trgm",
        "cheatsheet",
        [sa.literal_column("title gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cheatsheet_title_trgm", table_name="cheatsheet", postgresql_using="gin"
    )
    op.drop_index(
        "ix_cheatsheet_search_trgm", table_name="cheatsheet", postgresql_using="gin"
    )
    op.drop_index(
        "ix_cheatsheet_content_trgm", table_name="cheatsheet", postgresql_using="gin"
    )
    # ### end Alembic commands ###
