"""Make first_name, last_name, profile_description nullable,
add constraints for empty strings

Revision ID: 4602d7b5d589
Revises: 7b0e01730af0
Create Date: 2026-07-05 14:14:24.085863

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4602d7b5d589"
down_revision: Union[str, None] = "7b0e01730af0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_refresh_token_blacklist_hashed_token"),
        "refresh_token_blacklist",
        ["hashed_token"],
    )
    op.alter_column(
        "user_detail", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "user_detail", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "user_detail", "profile_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "user_detail", "image_url", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_detail", "image_url", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "user_detail", "profile_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "user_detail", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "user_detail", "first_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_constraint(
        op.f("uq_refresh_token_blacklist_hashed_token"),
        "refresh_token_blacklist",
        type_="unique",
    )
    # ### end Alembic commands ###
