"""Remove useless index from md_oauth_service table

Revision ID: 41991666ca26
Revises: 114ec0e874f7
Create Date: 2026-06-21 10:03:57.933343

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41991666ca26"
down_revision: Union[str, None] = "114ec0e874f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_service_name_lower"), table_name="md_oauth_service")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_oauth_service_name_lower"),
        "md_oauth_service",
        [sa.literal_column("lower(oauth_service_name::text)")],
        unique=True,
    )
    # ### end Alembic commands ###
