"""Add uniqueness to hashed_token column

Revision ID: 7b0e01730af0
Revises: 4651853d91ab
Create Date: 2026-07-03 17:27:17.692802

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b0e01730af0"
down_revision: Union[str, None] = "4651853d91ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_refresh_token_hashed_token"), "refresh_token", ["hashed_token"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_refresh_token_hashed_token"), "refresh_token", type_="unique"
    )
    # ### end Alembic commands ###
