"""Change Integer types

Revision ID: 2d3dc841c4e1
Revises: 1976419e3197
Create Date: 2026-05-16 11:11:55.868142

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d3dc841c4e1"
down_revision: Union[str, None] = "1f2a7fe2d4b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cheatsheet_to_tag",
        "tag_id",
        existing_type=sa.SMALLINT(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "md_tag",
        "tag_id",
        existing_type=sa.SMALLINT(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.Identity(
            always=True,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=32767,
            cycle=False,
            cache=1,
        ),
    )
    op.drop_constraint(
        op.f("fk_user_to_social_network_user_id_user"),
        "user_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_to_social_network_user_id_user_detail"),
        "user_to_social_network",
        "user_detail",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_to_social_network_user_id_user_detail"),
        "user_to_social_network",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_to_social_network_user_id_user"),
        "user_to_social_network",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "md_tag",
        "tag_id",
        existing_type=sa.BigInteger(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.Identity(
            always=True,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=32767,
            cycle=False,
            cache=1,
        ),
    )
    op.alter_column(
        "cheatsheet_to_tag",
        "tag_id",
        existing_type=sa.BigInteger(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
