"""Add provider_psuid into oauth_account, create oauth_refresh_token table

Revision ID: 114ec0e874f7
Revises: e0b33256e4bb
Create Date: 2026-06-19 19:06:22.653647

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "114ec0e874f7"
down_revision: Union[str, None] = "e0b33256e4bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_refresh_token",
        sa.Column(
            "refresh_token_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v7()"),
            nullable=False,
        ),
        sa.Column("oauth_account_id", sa.UUID(), nullable=False),
        sa.Column("status_id", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("hashed_token", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["oauth_account_id"],
            ["oauth_account.oauth_account_id"],
            name=op.f("fk_oauth_refresh_token_oauth_account_id_oauth_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["md_refresh_token_status.status_id"],
            name=op.f("fk_oauth_refresh_token_status_id_md_refresh_token_status"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "refresh_token_id", name=op.f("pk_oauth_refresh_token")
        ),
    )
    op.add_column(
        "oauth_account",
        sa.Column("provider_psuid", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_account", "provider_psuid")
    op.drop_table("oauth_refresh_token")
    # ### end Alembic commands ###
