"""create cheatsheets and tags tables

Revision ID: d6cb0b611442
Revises:
Create Date: 2025-05-31 22:19:16.941697

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6cb0b611442"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cheatsheet",
        sa.Column(
            "cheatsheet_id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("count_like", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("count_view", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "count_like >= 0",
            name=op.f("ck_cheatsheet_ck_count_like_positive"),
        ),
        sa.CheckConstraint(
            "count_view >= 0",
            name=op.f("ck_cheatsheet_ck_count_view_positive"),
        ),
        sa.PrimaryKeyConstraint("cheatsheet_id", name=op.f("pk_cheatsheet")),
        sa.UniqueConstraint("title", name=op.f("uq_cheatsheet_title")),
    )
    op.create_table(
        "md_tag",
        sa.Column("tag_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tag_name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("tag_id", name=op.f("pk_md_tag")),
        sa.UniqueConstraint("tag_name", name=op.f("uq_md_tag_tag_name")),
    )
    op.create_table(
        "cheatsheet_to_tag",
        sa.Column("cheatsheet_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cheatsheet_id"],
            ["cheatsheet.cheatsheet_id"],
            name=op.f("fk_cheatsheet_to_tag_cheatsheet_id_cheatsheet"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["md_tag.tag_id"],
            name=op.f("fk_cheatsheet_to_tag_tag_id_md_tag"),
        ),
        sa.PrimaryKeyConstraint(
            "cheatsheet_id", "tag_id", name=op.f("pk_cheatsheet_to_tag")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cheatsheet_to_tag")
    op.drop_table("md_tag")
    op.drop_table("cheatsheet")
    # ### end Alembic commands ###
